# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  RST-build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Update base system
        run: |
          sudo apt update
          sudo apt full-upgrade -y

      - name: Install required packages
        run: |
          sudo apt install texlive-latex-base texlive-extra-utils texlive-formats-extra wget

      - name: Manual pandoc install
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.11/pandoc-2.11-1-amd64.deb
          sudo dpkg -i pandoc-2.11-1-amd64.deb
          pandoc -v

      - name: Install python dependencies
        run: pip install pandocfilters


      - name: Generate slides for Ada fundamentals
        run: python pandoc/pandoc_fe.py --output-dir out/fundamentals_of_ada --hush --extension pdf --source courses/fundamentals_of_ada/*.rst

      - name: Generate slides for Ada fundamentals labs
        run: python pandoc/pandoc_fe.py --output-dir out/fundamentals_of_ada/labs --hush --extension pdf --source courses/fundamentals_of_ada/labs/*.rst

      - name: Package and upload Ada fundamental slides
        uses: actions/upload-artifact@v2
        with:
          name: Ada fundamentals
          path: out/fundamentals_of_ada/*.pdf

      - name: Package and upload Ada fundamental labs slides
        uses: actions/upload-artifact@v2
        with:
          name: Ada fundamentals Labs
          path: out/fundamentals_of_ada/labs/*.pdf

      - name: Generate standard Ada course
        run: python pandoc/pandoc_fe.py --extension pdf --source courses/fundamentals_of_ada/standard_course.txt --output-dir out/fundamentals_of_ada

      - name: Package and upload standard Ada course
        uses: actions/upload-artifact@v2
        with:
          name: Standard course
          path: out/fundamentals_of_ada/standard_course.pdf


      - name: Generate slides for Spark
        run: python pandoc/pandoc_fe.py --output-dir out/spark_for_ada_programmers --hush --extension pdf --source courses/spark_for_ada_programmers/*.rst

      - name: Package and upload Spark slides
        uses: actions/upload-artifact@v2
        with:
          name: Spark for Ada programmers
          path: out/spark_for_ada_programmers/*.pdf

      - name: Generate standard Spark course
        run: python pandoc/pandoc_fe.py --extension pdf --source courses/spark_for_ada_programmers/course.txt --output-dir out/spark_for_ada_programmers

      - name: Package and upload standard Spark course
        uses: actions/upload-artifact@v2
        with:
          name: Standard Spark course
          path: out/spark_for_ada_programmers/course.pdf

  labs-build:
    
    name: labs # intentionly short
    strategy:
      matrix:
        os: [ubuntu-latest] #windows-latest TODO

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/cache@v2
        with:
          path: ./cached_gnat
          key: ${{ runner.os }}-gnat-ce-2020

      - name: Get GNAT Community 2020 toolchain
        uses: ada-actions/toolchain@ce2020
        with:
          distrib: community
          install_dir: ./cached_gnat

      - name: Solution build for Ada Fundamentals
        run: python3 scripts/build_labs_check.py courses/fundamentals_of_ada
